### PR TITLE
Nft upload cleanup

### PR DESCRIPTION
**Pull request by korzewski**
This PR resolves this ticket https://www.notion.so/dot-matrix/1b047c821544433d8703f352d347b207?v=7a4133f9bd00425d8f6f7292ad2fe3a3&p=ffed1ae3824c4544a4dafacc36a5f59f

### CODE REVIEW

**Review by nblogist — DISMISSED** [review]

**Comment by nblogist** [comment]
@korzewski  please add a description of the pallet in its readme file, thank you!

**Comment by korzewski** [comment]
> @korzewski please add a description of the pallet in its readme file, thank you!

You want me to create new **README.md** file at **pallets/nft**?
How should it look like? Do you have any example?

**Comment by nblogist** [comment]
> How should it look like? Do you have any example?

Something like this:
https://github.com/hicommonwealth/edgeware-node/blob/master/pallets/orml-nft/README.md

**Review by justinfrevert — DISMISSED** [review]
Looks okay to me, though I may have less context on what can be removed.

**Comment by korzewski** [comment]
> > How should it look like? Do you have any example?
> 
> Something like this:
> https://github.com/hicommonwealth/edgeware-node/blob/master/pallets/orml-nft/README.md

Done

**Comment by nblogist** [comment]
Thanks! @korzewski, please re-request a review.

**Review by justinfrevert — APPROVED** [review]
👍

**Review by nblogist — APPROVED** [review]
Thanks for the PR @korzewski!

**Pull request merged**
